name: stepbystep
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  mac_address: ^1.0.0

  flutter_downloader: ^1.10.2
  dio: ^5.0.0
#  open_file:

  google_sign_in: ^5.4.0

  dotted_line: ^3.1.0

  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  firebase_core: ^1.23.0

  google_mobile_ads: ^1.2.0
  agora_rtc_engine: ^6.1.0
  provider: ^6.0.3

  form_field_validator: ^1.1.0

  date_picker_timeline: ^1.2.3
  flutter_date_picker_timeline: ^0.3.3
  image_picker: ^0.8.5
  firebase_storage: ^10.2.12
  velocity_x: ^3.4.0
  font_awesome_flutter: ^10.2.1

  table_calendar:

#  flutter_braintree: ^3.0.0

  readmore: ^2.2.0
  numberpicker: ^2.1.1
  date_format: ^2.0.2
  #Google Fonts
  google_fonts: ^3.0.1
  #For Shared Preferences
  flutter_secure_storage: ^5.0.2
  #Flutter toasts
  fluttertoast: ^8.0.9
  #show local notification
  flutter_local_notifications: ^9.4.0
  #native timezone
  flutter_native_timezone: ^2.0.0
  #listen for notification
  rxdart: ^0.27.1

  workmanager: ^0.5.0

  sqflite: ^2.0.2
  lottie:
  pull_to_refresh: ^2.0.0
  internet_connection_checker: ^0.0.1+1
  bot_toast: ^4.0.3
  flutter_swipe_action_cell: ^3.0.4
  syncfusion_flutter_charts: ^20.1.60+1
  overlay_support: ^1.2.1
  shimmer: ^2.0.0
  http: ^0.13.5
  firebase_messaging:
  carousel_slider: ^4.1.1

  flutter_chat_bubble: ^2.0.0
  emoji_picker_flutter:
  flutter_keyboard_visibility: ^5.4.0
  cached_network_image:

  file_picker: ^5.2.4
  flutter_share: ^2.0.0

  avatar_glow: ^2.0.2
  speech_to_text: ^6.1.1
  url_launcher: ^6.1.7
  record: ^4.4.4
  audioplayers: ^0.20.1
  assets_audio_player: ^3.0.4+3
  flutter_sound: ^9.2.13
  path_provider: ^2.0.11
  flutter_audio_recorder2:

  get: ^4.6.5



  image_downloader: ^0.31.0
  flutter_speed_dial: ^6.2.0
  flutter_colorpicker: ^1.0.3

  logger: ^1.1.0
  permission_handler: ^10.2.0
  smooth_page_indicator: ^1.0.0+2
  flutter_intro: ^3.0.2

  flutter_tts: ^3.6.3
#  alan_voice: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


  flutter_native_splash:
  flutter_launcher_icons: ^0.10.0


flutter_native_splash:
  color: "#ffffff"
  image: logos/StepByStep.png



flutter_icons:
  android: true
  ios: true
  image_path: "logos/logo.jpg"
  adaptive_icon_foreground: "logos/logo_foreground.png"
  adaptive_icon_background: "#ffffff"
  web:
    generate: true
  windows:
    generate: true



flutter:
  uses-material-design: true
  assets:
    - assets/
    - logos/
    - animations/

  fonts:
    - family: SegoeUI
      fonts:
        - asset: fonts/SEGOEUI.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: SegoeUIBold
      fonts:
        - asset: fonts/SegoeUIBold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
