name: stepbystep
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  mac_address: ^1.0.0

  google_sign_in: ^5.4.0

  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  firebase_core: ^1.23.0

  provider: ^6.0.3

  form_field_validator: ^1.1.0

  date_picker_timeline: ^1.2.3
  flutter_date_picker_timeline: ^0.3.3
  image_picker: ^0.8.5
  firebase_storage: ^10.2.12
  velocity_x: ^3.4.0
  font_awesome_flutter: ^10.2.1

  readmore: ^2.2.0
  numberpicker: ^2.1.1
  date_format: ^2.0.2
  #Google Fonts
  google_fonts: ^3.0.1
  #For Shared Preferences
  flutter_secure_storage: ^5.0.2
  #Flutter toasts
  fluttertoast: ^8.0.9
  #show local notification
  flutter_local_notifications: ^9.4.0
  #native timezone
  flutter_native_timezone: ^2.0.0
  #listen for notification
  rxdart: ^0.27.1

  workmanager: ^0.5.0

  sqflite: ^2.0.2
  lottie:
  pull_to_refresh: ^2.0.0
  internet_connection_checker: ^0.0.1+1
  bot_toast: ^4.0.3
  flutter_swipe_action_cell: ^3.0.4
  syncfusion_flutter_charts: ^20.1.60+1
  overlay_support: ^1.2.1
  shimmer: ^2.0.0
  http: ^0.13.5
  firebase_messaging:
  carousel_slider: ^4.1.1

  flutter_chat_bubble: ^2.0.0
  emoji_picker_flutter:
  flutter_keyboard_visibility: ^5.4.0
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


  flutter_native_splash:
  flutter_launcher_icons: ^0.10.0


flutter_native_splash:
  color: "#ffffff"
  image: logos/StepByStep.png



flutter_icons:
  android: true
  ios: true
  image_path: "logos/logo.jpg"
  adaptive_icon_foreground: "logos/logo_foreground.png"
  adaptive_icon_background: "#ffffff"
  web:
    generate: true
  windows:
    generate: true



flutter:
  uses-material-design: true
  assets:
    - assets/
    - logos/
    - animations/

  fonts:
    - family: SegoeUI
      fonts:
        - asset: fonts/SEGOEUI.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: SegoeUIBold
      fonts:
        - asset: fonts/SegoeUIBold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
